version:                   '3.3'

services:
  mariadb:
    image:                 mariadb:10.3.2
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE:      jazzy-wallboard
      MYSQL_USER:          devel
      MYSQL_PASSWORD:      devel
    ports:
      - "3306:3306"
    networks:
      - microservices

  jazzy-wallboard:
    image:                 build$CI_COMMIT_REF_NAME
    build:
      context:             ../
      args:
        ENVIRONMENT:       dev
    environment:
      DATABASE_HOST:       mariadb
      DATABASE_NAME:       jazzy-wallboard
      DATABASE_USER:       devel
      DATABASE_PASSWORD:   devel
    networks:
      - microservices

networks:
  microservices:
    driver:                bridge
